-- Truncate stations table and cascade delete on foreign keys
TRUNCATE TABLE stations RESTART IDENTITY CASCADE;

-- Insert generation stations
INSERT INTO stations (name, station_type) VALUES
  ('Shiroro', 'Generation'),
  ('Kainji', 'Generation'),
  ('Jebba', 'Generation'),
  ('Dadin-Kowa', 'Generation'),
  ('Zungeru', 'Generation'),
  ('Kashimbila', 'Generation'),
  ('Egbin', 'Generation'),
  ('Sapele Steam', 'Generation'),
  ('Delta', 'Generation'),
  ('Geregu Gas', 'Generation'),
  ('Omotosho Gas', 'Generation'),
  ('Olorunsogo Gas', 'Generation'),
  ('Afam III Fast Power (Bilateral)SBEE', 'Generation'),
  ('Trans Afam Power', 'Generation'),
  ('Sapele NIPP', 'Generation'),
  ('Alaoji NIPP', 'Generation'),
  ('Geregu NIPP', 'Generation'),
  ('Olorunsogo NIPP', 'Generation'),
  ('Omotosho NIPP', 'Generation'),
  ('Ihovbor NIPP', 'Generation'),
  ('Gbarain NIPP', 'Generation'),
  ('Odukpani NIP', 'Generation'),
  ('Okpai', 'Generation'),
  ('Afam VI', 'Generation'),
  ('AES', 'Generation'),
  ('MEPP', 'Generation'),
  ('GPAL', 'Generation'),
  ('Omoku', 'Generation'),
  ('Azura IPP', 'Generation'),
  ('Ibom', 'Generation'),
  ('Trans Amadi', 'Generation'),
  ('Rivers IPP', 'Generation'),
  ('Paras Energy', 'Generation'),
  ('Taopex Energy', 'Generation');
